USE apicarsdb;

CREATE TABLE brands (
    id INT PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE fuels (
    id INT PRIMARY KEY AUTOINCREMENT,
    type VARCHAR(50) NOT NULL
);

CREATE TABLE models (
    id INT PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    brand_id TINYINT NOT NULL UNSIGN,
    fuel_id TINYINT NOT NULL UNSIGN,
    FOREIGN KEY (brand_id) REFERENCES brands(id),
    FOREIGN KEY (fuel_id) REFERENCES fuels(id)
);