version: '3'

services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: node:16.15.1
    working_dir: /api
    container_name: api_cars_with_db
    restart: always
    volumes:
      - ./:/api
    ports:
      - 3001:3001
    depends_on:
      - database
  
  database:
    image: mysql:8.0.29
    container_name: database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root(password)
      - MYSQL_DATABASE=apicarsdb
    ports:
      - 3306:3306
    volumes:
      - ./api_cars.sql:/docker-entrypoint-initdb.d/api_cars.sql
      - ./.dataDB:/var/lib/mysql

volumes:
  .dataDB: